### ISSUE TITLE
Namespacing support

### ISSUE THREAD

**Issue by habibalamin** [brandur/sinatra-router#2]
I couldn't get any of these to work:

```ruby
use Sinatra::Router do
  mount AppToHandleAssets => '/assets'
end
```

```ruby
# using sinatra-namespace
# this doesn't involve sinatra-router
namespace '/assets' do
  use AppToHandleAssets
end
```

```ruby
# using sinatra-namespace
namespace '/assets' do
  use Sinatra::Router do
    mount AppToHandleAssets
  end
end
```

```ruby
# this doesn't involve sinatra-router
use Rack::URLMap.new '/assets' => AppToHandleAssets.new
```

I ended up just using `#map` within `config.ru`, but then I have routing logic in multiple places.

**Comment by brandur** [comment]
Hi there,

sinatra-router is designed to be used from the Rack level rather than from inside a Sinatra app, so what you did by using Rack::Builder's `#map` is actually the right option here.

What do you mean exactly that you ended up with duplicate routing logic? What should happen is that the prefix given to `#map` gets stripped before being handed off to a `Sinatra::Router` so your routes should stay DRY.

**Comment by habibalamin** [comment]
What I meant by duplication is that I was using `#map` in `config.ru`, but then I was using `Sinatra::Router` in my main app file to split my code into controllers (basically other Sinatra apps).

**Comment by brandur** [comment]
Ah! And is your main app here a Sinatra instance itself?

What I usually recommend is making the "main" app a Rack builder instance itself (forgive me if this syntax isn't entirely correct, it's written from memory).

``` ruby
MyApp = Rack::Builder.new do
  map "/my-app" do
    run Sinatra::Router {
      mount App1
      mount App2
      mount App3
    }
  end
end
```

And then in `config.ru`:

``` ruby
require "my_app"
run MyApp
```

**Comment by habibalamin** [comment]
Yes, it is.

Ah, I see. I think the name must have confused me. So, really, the gem has nothing to do with Sinatra itself? It's not meant to be used within Sinatra as a middleware or anything like that, it's just a router ‘marketed’, if you will, towards Sinatra users, but really intended for Rack users who need a router.

**Comment by brandur** [comment]
Yeah, it's possible it's not explained well, but the idea is that it's a router _to_ (or _for_) Sinatra. Multiple Sinatra apps can be plugged into it so that you can compose them into one larger app.

**Comment by brandur** [comment]
Going to close this issue down! Let me know if you have any other questions/comments. Thanks!
