### ISSUE TITLE
 NoMethodError: undefined method `call' for Sinatra::Router:Class

### ISSUE THREAD

**Issue by stereobooster** [brandur/sinatra-router#7]
Having following code

```ruby
module Routes
  Root = Rack::Builder.app do
    map "/" do
      run Sinatra::Router do
        mount SinatraApp1
        mount SinatraApp2

```

Feel like there is some stupid error

**Comment by brandur** [comment]
If I recall correctly, there are some block operator precedence issues with `Rack::Builder` sometime. Can you try curly braces instead of `do/end` notation?

Failing that, possibly try to take out certain elements (e.g. `Rack::Builder`, `map`) and re-running to see if you can localize the problem.

**Comment by stereobooster** [comment]
it is 

```ruby
Root = Rack::Builder.new do
  use Sinatra::Router do
     mount SinatraApp1
     mount SinatraApp2
  end
end
```

related https://github.com/sinatra/sinatra/issues/1296
